/*

 LONG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 2
   Map size      : 100 x 18
   Tile set      : Z:\home\agrobenj\MIE438_Project\sprites\background_tiles_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define long_mapWidth 100
#define long_mapHeight 18
#define long_mapBank 2

extern unsigned char long_map[];

/* End of LONG_MAP.H */
