/*

 SIMPLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : Z:\home\agrobenj\MIE438_Project\sprites\background_tiles_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define simple_mapWidth 40
#define simple_mapHeight 18
#define simple_mapBank 0

extern unsigned char simple_map[];

/* End of SIMPLE_MAP.H */
