/*

 LEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 2
   Map size      : 256 x 18
   Tile set      : Z:\home\agrobenj\MIE438_Project\sprites\src\gb_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level1_h_INCLUDE
#define __level1_h_INCLUDE

#define level1Width 256
#define level1Height 18
#define level1Bank 3

extern const unsigned char level1[];

#endif

/* End of LEVEL1.H */
