/*

 LEVEL1_V2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 512 x 18
   Tile set      : gb_tileset_v2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level1_v2_h_INCLUDE
#define __level1_v2_h_INCLUDE

#define level1_v2Width 512
#define level1_v2Height 18
#define level1_v2Bank 3

extern const unsigned char level1_v2[];

#endif

/* End of LEVEL1_V2.H */
