/*

 LEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : Z:\home\agrobenj\MIE438_Project\sprites\background_tiles_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level1Width 40
#define level1Height 18
#define level1Bank 0

extern const unsigned char level1[];

/* End of LEVEL1.H */
