/*

 PARALLAX_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\agrobenj\MIE438_Project\sprites\parallax_test_2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define parallax_mapWidth 20
#define parallax_mapHeight 18
#define parallax_mapBank 0

extern unsigned char parallax_map[];

/* End of PARALLAX_MAP.H */
