/*

 PARRALLAX_TILES_1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define parrallax_tiles_1Bank 0
/* Start of tile array. */
extern unsigned char parrallax_tiles_1[];

/* End of PARRALLAX_TILES_1.H */
