/*

 TEST_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : Z:\home\agrobenj\MIE438_Project\sprites\background_tiles_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define test_mapWidth 40
#define test_mapHeight 18
#define test_mapBank 2

extern const unsigned char test_map[];

/* End of TEST_MAP.H */
