/*

 BACK_SPIKE_PARALLAX.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __back_spike_parallax_h_INCLUDE
#define __back_spike_parallax_h_INCLUDE

/* Bank of tiles. */
#define back_spike_parallaxBank 2
/* Start of tile array. */
extern const void __bank_back_spike_parallax;
extern const unsigned char back_spike_parallax[];

#endif

/* End of BACK_SPIKE_PARALLAX.H */
