/*

 GB_TILESET_V2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __gb_tileset_v2_h_INCLUDE
#define __gb_tileset_v2_h_INCLUDE

/* Bank of tiles. */
#define gb_tileset_v2Bank 0
/* Start of tile array. */
extern const unsigned char gb_tileset_v2[];

#endif

/* End of GB_TILESET_V2.H */
