/*

 HALF_BLOCK_PARALLAX.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __half_block_parallax_h_INCLUDE
#define __half_block_parallax_h_INCLUDE

/* Bank of tiles. */
#define half_block_parallaxBank 2
/* Start of tile array. */
extern const void __bank_half_block_parallax;
extern const unsigned char half_block_parallax[];

#endif

/* End of HALF_BLOCK_PARALLAX.H */
