/*

 LEVEL_TEMPLATE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 455 x 18
   Tile set      : gb_tileset_v2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level_template_h_INCLUDE
#define __level_template_h_INCLUDE

#define level_templateWidth 455
#define level_templateHeight 18
#define level_templateBank 4

extern const unsigned char level_template[];

#endif

/* End of LEVEL_TEMPLATE.H */
