/*

 LEVEL3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 5
   Map size      : 455 x 18
   Tile set      : gb_tileset_v2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level3_h_INCLUDE
#define __level3_h_INCLUDE

#define level3Width 455
#define level3Height 18
#define level3Bank 5

extern const unsigned char level3[];

#endif

/* End of LEVEL3.H */
