/*

 LEVEL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 455 x 18
   Tile set      : gb_tileset_v2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level2_h_INCLUDE
#define __level2_h_INCLUDE

#define level2Width 455
#define level2Height 18
#define level2Bank 4

extern const unsigned char level2[];

#endif

/* End of LEVEL2.H */
