/*

 PARALLAX_TILESET_V2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __parallax_tileset_v2_h_INCLUDE
#define __parallax_tileset_v2_h_INCLUDE

/* Bank of tiles. */
#define parallax_tileset_v2Bank 2
/* Start of tile array. */
extern const void __bank_parallax_tileset_v2;
extern const unsigned char parallax_tileset_v2[];

#endif

/* End of PARALLAX_TILESET_V2.H */
