/*

 SHIP_PARALLAX.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ship_parallax_h_INCLUDE
#define __ship_parallax_h_INCLUDE

/* Bank of tiles. */
#define ship_parallaxBank 2
/* Start of tile array. */
extern const void __bank_ship_parallax;
extern const unsigned char ship_parallax[];

#endif

/* End of SHIP_PARALLAX.H */
