/*

 TITLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 2
   Map size      : 60 x 18
   Tile set      : Z:\home\agrobenj\MIE438_Project\sprites\src\gb_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __title_map_h_INCLUDE
#define __title_map_h_INCLUDE

#define title_mapWidth 60
#define title_mapHeight 18
#define title_mapBank 2

extern const unsigned char title_map[];

#endif

/* End of TITLE_MAP.H */
