/*

 TITLE_MAP_V2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 60 x 18
   Tile set      : gb_tileset_v2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __title_map_v2_h_INCLUDE
#define __title_map_v2_h_INCLUDE

#define title_map_v2Width 60
#define title_map_v2Height 18
#define title_map_v2Bank 3

extern const unsigned char title_map_v2[];

#endif

/* End of TITLE_MAP_V2.H */
